//! Shadow inference: tract-powered ONNX observation with NO macro control
//! (v5.4.0 plan).
//!
//! Control-impossibility is structural, not promised:
//! - `preprocess_rgba` / `infer_logits` / `softmax_temp` are pure functions
//!   of pixels. They receive no `Ctx`, no input handles, no settings.
//! - The global engine only loads models and runs them; callers (machine.rs)
//!   may LOG the observations and nothing else.
//! - The production provider (`ml_model.rs`) is untouched: `available()`
//!   stays false, so nothing here can activate control.
//! - Every loaded model carries its manifest revision, so shadow telemetry is
//!   attributable to specific weights: a candidate promoted over a slot
//!   (same stem) cannot inherit the displaced model's soak evidence.
//!
//! Preprocessing MUST equal training preprocessing (pad-to-square black,
//! bilinear resize, /255, dataset mean/std — see each model's manifest
//! `preprocess` block, generated by scripts/gen_shadow_deploy.py from the
//! real run configs). Equivalence is proven by the fixture test below
//! (PIL BILINEAR vs this manual bilinear: tolerance 5e-3, argmax exact).

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use serde::{Deserialize, Serialize};
use tract_onnx::prelude::*;

use super::ml_model::verify_weights;

/// Files bundled with the app that may seed `%APPDATA%/models/`.
pub const SHADOW_MODEL_FILES: &[(&str, &str)] =
    &[("state_v1.onnx", "state_v1.json"), ("fish_v1.onnx", "fish_v1.json")];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreprocessSpec {
    pub pad: String,
    pub resize: String,
    pub size: usize,
    pub mean: [f32; 3],
    pub std: [f32; 3],
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ShadowManifest {
    #[serde(flatten)]
    base: super::ml_model::ModelManifest,
    temperature: f32,
    #[serde(default)]
    test_accuracy: Option<f32>,
    preprocess: PreprocessSpec,
}

/// Concrete tract session type (fact/op/plan pinned for this build).
pub type ShadowSession =
    RunnableModel<TypedFact, Box<dyn TypedOp>, Graph<TypedFact, Box<dyn TypedOp>>>;

pub struct ShadowModel {
    /// Shadow slot stem (e.g. `fish_v1`). CONSTANT per slot: promoting a new
    /// candidate overwrites these weights under the same name, so the stem
    /// alone does not identify weights.
    pub name: String,
    /// Manifest `version`, stringified. The revision half of the model's
    /// identity: the stem says WHICH slot, this says WHICH weights.
    pub revision: String,
    pub classes: Vec<String>,
    pub temperature: f32,
    pub test_accuracy: Option<f32>,
    pub spec: PreprocessSpec,
    session: ShadowSession,
}

impl ShadowModel {
    /// Revision-aware identity, `<stem>@<revision>` (e.g. `fish_v1@2`). The
    /// revision half is the raw manifest `version` string (no normalization)
    /// so it equals the on-disk join key exactly. Two loads of the same slot
    /// with different revisions are different models; never join telemetry on
    /// the stem alone.
    pub fn identity(&self) -> String {
        format!("{}@{}", self.name, self.revision)
    }

    /// The revision half alone: the shadow-log grouping key that keeps a
    /// newly promoted candidate's soak separate from the incumbent's.
    pub fn identity_revision(&self) -> String {
        self.revision.clone()
    }
}

pub struct ShadowEngine {
    pub models_dir: PathBuf,
    pub models: HashMap<String, ShadowModel>,
}

/// Manifest `version` -> revision string. Strings pass through trimmed,
/// numbers are stringified, and an absent/empty field becomes `"0"` so a
/// manifest written before revisions existed still loads with a defined
/// (unversioned) identity instead of colliding with a numbered one.
pub fn revision_from_manifest(manifest: &serde_json::Value) -> String {
    match manifest.get("version") {
        Some(serde_json::Value::String(s)) if !s.trim().is_empty() => s.trim().to_string(),
        Some(serde_json::Value::Number(n)) => n.to_string(),
        _ => "0".to_string(),
    }
}

fn load_one(models_dir: &Path, onnx_name: &str, json_name: &str) -> Result<ShadowModel, String> {
    let json_path = models_dir.join(json_name);
    let onnx_path = models_dir.join(onnx_name);
    let raw = std::fs::read_to_string(&json_path).map_err(|e| format!("{json_name}: {e}"))?;
    let m: ShadowManifest =
        serde_json::from_str(&raw).map_err(|e| format!("{json_name} invalid: {e}"))?;
    // Revision is read from the raw document (not the typed field) so numeric
    // versions and a missing/empty version both resolve deterministically.
    let revision = revision_from_manifest(
        &serde_json::from_str::<serde_json::Value>(&raw).unwrap_or(serde_json::Value::Null),
    );
    if m.base.runtime != "tract" {
        return Err(format!("{}: runtime '{}' is not this tract build", json_name, m.base.runtime));
    }
    verify_weights(&m.base, &onnx_path.to_path_buf()).map_err(|e| e.to_string())?;
    let mut typed = tract_onnx::onnx()
        .model_for_path(&onnx_path)
        .map_err(|e| format!("{onnx_name} load: {e}"))?;
    typed
        .set_input_fact(0, f32::fact([1, 3, m.preprocess.size, m.preprocess.size]).into())
        .map_err(|e| format!("{onnx_name} input fact: {e}"))?;
    // NOTE: no into_optimized(): the dynamo-exported graph contains a Conv
    // formulation whose optimizer analysis tract 0.22 rejects (ConvHir).
    // into_typed + into_runnable executes the same semantics without the
    // failing optimizer pass; the fixture argmax test below proves
    // end-to-end agreement with torch.
    let session = typed
        .into_typed()
        .map_err(|e| format!("{onnx_name} typed: {e}"))?
        .into_runnable()
        .map_err(|e| format!("{onnx_name} runnable: {e}"))?;
    // Shape-check: single output of [1, n_classes].
    Ok(ShadowModel {
        name: m.base.name.clone(),
        revision,
        classes: m.base.classes.clone(),
        temperature: m.temperature,
        test_accuracy: m.test_accuracy,
        spec: m.preprocess,
        session,
    })
}

impl ShadowEngine {
    /// Load every deployable shadow model from `models_dir`. Missing files
    /// are skipped (engine still usable with the rest); corrupt files are
    /// errors (never silently run wrong weights).
    pub fn load(models_dir: &Path) -> Result<Self, String> {
        let mut models = HashMap::new();
        let mut missing = 0;
        for (onnx, json) in SHADOW_MODEL_FILES {
            if !models_dir.join(json).exists() || !models_dir.join(onnx).exists() {
                missing += 1;
                continue;
            }
            let m = load_one(models_dir, onnx, json)?;
            // FAMILY INTEGRITY. The map key must be the SLOT, not whatever
            // the manifest claims. Otherwise a fish manifest copied over the
            // state files inserts under "fish_v1", silently EVICTS the real
            // fish entry, and `models.get("state_v1")` returns None forever -
            // state shadow observation stops with no error and readiness still
            // reads a perfectly valid state_v1.json off disk.
            let expected = onnx.trim_end_matches(".onnx").to_string();
            if m.name != expected {
                return Err(format!(
                    "{json} declares model '{}' but occupies slot '{expected}'; \\
                     refusing to load (a model family cannot cross slots)",
                    m.name
                ));
            }
            if models.insert(m.name.clone(), m).is_some() {
                return Err(format!("duplicate shadow model '{expected}'"));
            }
        }
        if models.is_empty() {
            return Err(format!("no shadow models in {}", models_dir.display()));
        }
        tracing::info!("shadow inference: loaded {} model(s) ({} missing)", models.len(), missing);
        Ok(Self { models_dir: models_dir.to_path_buf(), models })
    }

    pub fn model_names(&self) -> Vec<String> {
        let mut v: Vec<String> = self.models.keys().cloned().collect();
        v.sort();
        v
    }

    /// Pure inference: CHW pixels -> class probabilities. No side effects.
    pub fn infer_probs(&self, name: &str, chw: &[f32]) -> Option<Vec<(String, f32)>> {
        let m = self.models.get(name)?;
        let s = m.spec.size;
        if chw.len() != 3 * s * s {
            return None;
        }
        let shape = [1, 3, s, s];
        let input = Tensor::from_shape(&shape, chw).ok()?;
        let out = m.session.run(tvec![input.into()]).ok()?;
        let logits = out[0].to_array_view::<f32>().ok()?;
        let flat: Vec<f32> = logits.iter().cloned().collect();
        if flat.len() != m.classes.len() {
            return None;
        }
        let probs = softmax_temp(&flat, m.temperature);
        Some(m.classes.iter().cloned().zip(probs).collect())
    }
}

/// RGBA frame -> CHW model input. Manual bilinear with PIL-compatible
/// center mapping: src=(dst+0.5)*scale-0.5, edge-clamped.
pub fn preprocess_rgba(rgba: &[u8], w: usize, h: usize, spec: &PreprocessSpec) -> Option<Vec<f32>> {
    if rgba.len() < w * h * 4 || w == 0 || h == 0 {
        return None;
    }
    // RGB, then pad to square (black).
    let side = w.max(h);
    let mut sq = vec![0u8; side * side * 3];
    for y in 0..h {
        for x in 0..w {
            let s = (y * w + x) * 4;
            let dx = (side - w) / 2 + x;
            let dy = (side - h) / 2 + y;
            let d = (dy * side + dx) * 3;
            sq[d] = rgba[s];
            sq[d + 1] = rgba[s + 1];
            sq[d + 2] = rgba[s + 2];
        }
    }
    // Bilinear resize to size x size, per channel.
    let n = spec.size;
    let mut out = vec![0f32; 3 * n * n];
    let sx = side as f32 / n as f32;
    let sy = side as f32 / n as f32;
    for c in 0..3 {
        for dy in 0..n {
            let src_y = (dy as f32 + 0.5) * sy - 0.5;
            let y0 = (src_y.floor() as isize).clamp(0, side as isize - 1) as usize;
            let y1 = (y0 + 1).min(side - 1);
            let fy = (src_y - y0 as f32).clamp(0.0, 1.0);
            for dx in 0..n {
                let src_x = (dx as f32 + 0.5) * sx - 0.5;
                let x0 = (src_x.floor() as isize).clamp(0, side as isize - 1) as usize;
                let x1 = (x0 + 1).min(side - 1);
                let fx = (src_x - x0 as f32).clamp(0.0, 1.0);
                let at = |xx: usize, yy: usize| sq[(yy * side + xx) * 3 + c] as f32 / 255.0;
                let v = at(x0, y0) * (1.0 - fx) * (1.0 - fy)
                    + at(x1, y0) * fx * (1.0 - fy)
                    + at(x0, y1) * (1.0 - fx) * fy
                    + at(x1, y1) * fx * fy;
                out[(c * n + dy) * n + dx] = (v - spec.mean[c]) / spec.std[c];
            }
        }
    }
    Some(out)
}

pub fn softmax_temp(logits: &[f32], temperature: f32) -> Vec<f32> {
    let t = temperature.max(1e-6);
    let m = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let ex: Vec<f32> = logits.iter().map(|v| ((v - m) / t).exp()).collect();
    let s: f32 = ex.iter().sum();
    ex.iter().map(|v| v / s).collect()
}

static ENGINE: OnceLock<Mutex<ShadowEngine>> = OnceLock::new();

/// Get-or-load the process-wide shadow engine. First call pays model load.
pub fn engine(models_dir: &Path) -> Option<std::sync::MutexGuard<'static, ShadowEngine>> {
    let cell = ENGINE.get_or_init(|| {
        Mutex::new(ShadowEngine { models_dir: models_dir.to_path_buf(), models: HashMap::new() })
    });
    let mut guard = cell.lock().ok()?;
    if guard.models.is_empty() {
        match ShadowEngine::load(models_dir) {
            Ok(e) => *guard = e,
            Err(err) => {
                tracing::warn!("shadow inference unavailable: {err}");
                return None;
            }
        }
    }
    Some(guard)
}

/// Read the manifest `version` field as a number. `None` when absent or
/// unparseable (which is treated as "not a promoted candidate").
fn manifest_version(path: &Path) -> Option<u64> {
    let raw = std::fs::read_to_string(path).ok()?;
    let v: serde_json::Value = serde_json::from_str(&raw).ok()?;
    match v.get("version")? {
        serde_json::Value::Number(n) => n.as_u64(),
        serde_json::Value::String(s) => s.trim().parse::<u64>().ok(),
        _ => None,
    }
}

/// Drop the cached engine so the next `engine()` call re-reads the models
/// directory. Called when the deployed bytes change (seeding or promotion);
/// without this the process keeps running the weights it loaded at startup
/// and stamps telemetry with the wrong revision.
pub fn invalidate_engine() {
    if let Some(cell) = ENGINE.get() {
        if let Ok(mut guard) = cell.lock() {
            guard.models.clear();
        }
    }
}

/// Seed `%APPDATA%/models` from bundled candidates. Copies a file only when
/// missing, checksum-divergent, or strictly older than what is deployed.
/// Allowlist enforced.
pub fn seed_shadow_models(candidates: &[PathBuf], models_dir: &Path) -> Vec<String> {
    let _ = std::fs::create_dir_all(models_dir);
    let mut seeded = Vec::new();
    for (onnx, json) in SHADOW_MODEL_FILES {
        let src_json = candidates.iter().map(|c| c.join(json)).find(|p| p.exists());
        let src_onnx = candidates.iter().map(|c| c.join(onnx)).find(|p| p.exists());
        let (Some(sj), Some(so)) = (src_json, src_onnx) else { continue };
        let want_json = std::fs::read(&sj).unwrap_or_default();
        let want_onnx = std::fs::read(&so).unwrap_or_default();
        if want_json.is_empty() || want_onnx.is_empty() {
            continue;
        }
        let dj = models_dir.join(json);
        let do_ = models_dir.join(onnx);
        let same = std::fs::read(&dj).map(|b| b == want_json).unwrap_or(false)
            && std::fs::read(&do_).map(|b| b == want_onnx).unwrap_or(false);
        // NEVER downgrade a deployed candidate. A promoted model has a
        // manifest `version` above the bundled one; overwriting it on the next
        // launch would silently restore the old weights while the registry
        // still claims the candidate is shadowed - and the soak for the old
        // revision is already populated. Promotion must survive a restart.
        if !same {
            if let Some(existing) = manifest_version(&dj) {
                let bundled = manifest_version(&sj).unwrap_or(0);
                if existing > bundled {
                    tracing::info!(
                        "shadow seed: keeping deployed {onnx} v{existing} (bundled is v{bundled})"
                    );
                    match load_one(models_dir, onnx, json) {
                        Ok(_) => seeded.push(onnx.to_string()),
                        Err(e) => tracing::warn!("shadow seed: deployed {onnx} rejected: {e}"),
                    }
                    continue;
                }
            }
            if std::fs::write(&dj, &want_json).is_err()
                || std::fs::write(&do_, &want_onnx).is_err()
            {
                tracing::warn!("shadow seed: write failed for {onnx}");
                continue;
            }
            // The deployed bytes changed: drop the cached engine so the next
            // inference actually loads what is on disk.
            invalidate_engine();
        }
        // Verify what is on disk (seeded or pre-existing) before trusting.
        match load_one(models_dir, onnx, json) {
            Ok(_) => seeded.push(onnx.to_string()),
            Err(e) => tracing::warn!("shadow seed: deployed {onnx} rejected: {e}"),
        }
    }
    seeded
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/shadow")
    }

    fn read_f32(name: &str) -> Vec<f32> {
        let bytes = std::fs::read(fixture_dir().join(name)).unwrap();
        assert_eq!(bytes.len() % 4, 0);
        bytes.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
    }

    fn spec_for(model: &str) -> PreprocessSpec {
        let raw = std::fs::read_to_string(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!("models/{model}.json")),
        )
        .unwrap();
        let v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let p = &v["preprocess"];
        let arr = |k: &str| -> [f32; 3] {
            let a = p[k].as_array().unwrap();
            [a[0].as_f64().unwrap() as f32, a[1].as_f64().unwrap() as f32, a[2].as_f64().unwrap() as f32]
        };
        PreprocessSpec {
            pad: p["pad"].as_str().unwrap().into(),
            resize: p["resize"].as_str().unwrap().into(),
            size: p["size"].as_u64().unwrap() as usize,
            mean: arr("mean"),
            std: arr("std"),
        }
    }

    #[test]
    fn preprocess_matches_python_fixture() {
        let png = std::fs::read(fixture_dir().join("fixture.png")).unwrap();
        let img = image::load_from_memory(&png).unwrap().to_rgba8();
        let (w, h) = (img.width() as usize, img.height() as usize);
        let meta: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(fixture_dir().join("expected.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(meta["png_sha256"].as_str().unwrap(), &{
            // cross-check the fixture itself via the repo's sha helper
            super::super::ml_model::sha256_file(&fixture_dir().join("fixture.png")).unwrap()
        });
        for model in ["state_v1", "fish_v1"] {
            let spec = spec_for(model);
            let got = preprocess_rgba(img.as_raw(), w, h, &spec).unwrap();
            let want = read_f32(&format!("{model}.f32"));
            assert_eq!(got.len(), want.len());
            let worst = got.iter().zip(want.iter()).map(|(a, b)| (a - b).abs()).fold(0f32, f32::max);
            let tol = meta["tolerance_max_abs_diff"].as_f64().unwrap() as f32;
            assert!(worst < tol, "{model} preprocess drift: worst {worst} >= tol {tol}");
        }
    }

    #[test]
    fn deployed_models_predict_fixture_argmax() {
        let models_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        let engine = match ShadowEngine::load(&models_dir) {
            Ok(e) => e,
            Err(e) => panic!("repo models must load: {e}"),
        };
        let png = std::fs::read(fixture_dir().join("fixture.png")).unwrap();
        let img = image::load_from_memory(&png).unwrap().to_rgba8();
        let (w, h) = (img.width() as usize, img.height() as usize);
        let meta: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(fixture_dir().join("expected.json")).unwrap(),
        )
        .unwrap();
        for model in ["state_v1", "fish_v1"] {
            let spec = spec_for(model);
            let chw = preprocess_rgba(img.as_raw(), w, h, &spec).unwrap();
            let probs = engine.infer_probs(model, &chw).expect("infer must succeed");
            let (best, _) =
                probs.iter().max_by(|a, b| a.1.partial_cmp(&b.1).unwrap()).unwrap();
            let want_idx = meta["argmax"][model].as_u64().unwrap() as usize;
            let want_class = &engine.models[model].classes[want_idx];
            assert_eq!(best, want_class, "{model} argmax diverged from torch (preprocess or runtime drift)");
        }
    }

    #[test]
    fn corrupt_weights_never_load() {
        let dir = std::env::temp_dir().join("gpo-shadow-corrupt");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        std::fs::copy(repo.join("state_v1.json"), dir.join("state_v1.json")).unwrap();
        // Truncated weights: manifest sha will not match.
        let w = std::fs::read(repo.join("state_v1.onnx")).unwrap();
        std::fs::write(dir.join("state_v1.onnx"), &w[..w.len() / 2]).unwrap();
        let err = match ShadowEngine::load(&dir) {
            Ok(_) => panic!("corrupt weights must refuse to load"),
            Err(e) => e,
        };
        // Contract: corrupt files are hard errors (checksum), never silent.
        assert!(err.contains("checksum mismatch"), "corrupt weights must refuse: {err}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn seeding_deploys_verifiable_models() {
        let dir = std::env::temp_dir().join("gpo-shadow-seed");
        let _ = std::fs::remove_dir_all(&dir);
        let repo_models = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        let seeded = seed_shadow_models(&[repo_models], &dir.join("models"));
        assert_eq!(seeded.len(), 2, "both bundled models must seed, got {seeded:?}");
        // Seeded copies load and stay byte-identical (no silent rewrite).
        let engine = match ShadowEngine::load(&dir.join("models")) {
            Ok(e) => e,
            Err(e) => panic!("seeded models must load: {e}"),
        };
        assert_eq!(engine.models.len(), 2);
        // Second seed is a no-op rewrite-wise but still verifies.
        let seeded2 = seed_shadow_models(
            &[PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models")],
            &dir.join("models"),
        );
        assert_eq!(seeded2.len(), 2);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn softmax_temp_matches_definition() {
        let p = softmax_temp(&[2.0, 1.0, 0.0], 1.0);
        let s: f32 = p.iter().sum();
        assert!((s - 1.0).abs() < 1e-6);
        assert!(p[0] > p[1] && p[1] > p[2]);
        // Lower temperature sharpens.
        let sharp = softmax_temp(&[2.0, 1.0, 0.0], 0.15);
        assert!(sharp[0] > p[0]);
    }

    #[test]
    fn revision_is_read_from_the_manifest_version() {
        // Strings pass through; numbers are stringified; absent/empty falls
        // back to "0" so a pre-revision manifest still has a defined identity
        // (and cannot collide with a numbered revision).
        assert_eq!(revision_from_manifest(&serde_json::json!({"version": "2"})), "2");
        assert_eq!(revision_from_manifest(&serde_json::json!({"version": " 7 "})), "7");
        assert_eq!(revision_from_manifest(&serde_json::json!({"version": 12})), "12");
        assert_eq!(revision_from_manifest(&serde_json::json!({"version": ""})), "0");
        assert_eq!(revision_from_manifest(&serde_json::json!({"version": null})), "0");
        assert_eq!(revision_from_manifest(&serde_json::json!({"name": "fish_v1"})), "0");
        assert_eq!(revision_from_manifest(&serde_json::Value::Null), "0");
    }

    #[test]
    fn model_identity_is_stem_at_revision() {
        let models_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        let engine = match ShadowEngine::load(&models_dir) {
            Ok(e) => e,
            Err(e) => panic!("repo models must load: {e}"),
        };
        for model in ["state_v1", "fish_v1"] {
            let m = &engine.models[model];
            // Identity names the weights, not just the slot.
            assert_eq!(m.identity(), format!("{model}@{}", m.revision));
            assert_eq!(m.identity_revision(), m.revision);
            assert!(!m.revision.is_empty());
            // ...and it matches the on-disk manifest it was loaded from.
            let raw: serde_json::Value = serde_json::from_str(
                &std::fs::read_to_string(models_dir.join(format!("{model}.json"))).unwrap(),
            )
            .unwrap();
            assert_eq!(m.revision, revision_from_manifest(&raw), "{model} revision drift");
        }
        // A promotion rewrites the manifest with a bumped `version` and the
        // SAME stem: the identity must change even though the slot does not.
        // The revision half is the RAW manifest version string (no "v"
        // normalization) so it equals the on-disk join key exactly.
        let promoted = serde_json::json!({"name": "fish_v1", "version": "2"});
        let rev = revision_from_manifest(&promoted);
        assert_eq!(rev, "2");
        assert_eq!(format!("{}@{}", "fish_v1", rev), "fish_v1@2");
        // A manifest whose version is literally "v2" keeps that spelling.
        let v_spelled = revision_from_manifest(&serde_json::json!({"version": "v2"}));
        assert_eq!(format!("{}@{}", "fish_v1", v_spelled), "fish_v1@v2");
    }

    /// A real, loadable bundled manifest with `name` rewritten.
    fn slot_manifest(name: &str, version: &str) -> serde_json::Value {
        let raw = std::fs::read_to_string(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models/state_v1.json"),
        )
        .unwrap();
        let mut v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        v["name"] = serde_json::Value::String(name.to_string());
        v["version"] = serde_json::Value::String(version.to_string());
        v
    }

    /// Copy the real bundled state model into `dir` under the fish names, with
    /// the manifest's declared `name` left as the STATE stem. That is exactly
    /// the substitution that used to go unnoticed.
    fn plant_cross_family(dir: &Path, declared_name: &str) {
        let models = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        std::fs::create_dir_all(dir).unwrap();
        for (from, to) in [
            ("state_v1.onnx", "state_v1.onnx"),
            ("fish_v1.onnx", "fish_v1.onnx"),
        ] {
            let _ = std::fs::copy(models.join(from), dir.join(to));
        }
        // state_v1.json declares "fish_v1": a family/name mismatch.
        std::fs::write(
            dir.join("state_v1.json"),
            serde_json::to_string_pretty(&slot_manifest(declared_name, "9")).unwrap(),
        )
        .unwrap();
        // fish_v1.json is left absent, so `fish_v1` itself never loads.
    }

    #[test]
    fn a_manifest_may_not_occupy_another_familys_slot() {
        // The v5.6.x bug: the engine map was keyed by the manifest's
        // self-declared name, so this manifest inserted under "fish_v1" and
        // EVICTED the real fish entry - state shadow observation then stopped
        // permanently with no error, while readiness kept reading a perfectly
        // valid state_v1.json off disk.
        let dir = std::env::temp_dir().join("gpo-shadow-slot-mix");
        let _ = std::fs::remove_dir_all(&dir);
        plant_cross_family(&dir, "fish_v1");

        match ShadowEngine::load(&dir) {
            Ok(_) => panic!("a manifest occupying another family's slot must be refused"),
            Err(e) => {
                assert!(
                    e.contains("cannot cross slots") || e.contains("no shadow models"),
                    "must name the slot problem: {e}"
                );
            }
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn revision_identity_is_stable_and_distinct_per_version() {
        // The identity must be derivable from the manifest alone: it is the
        // join key between "which weights" and "which soak events".
        let v1 = serde_json::json!({"version": "1"});
        let v2 = serde_json::json!({"version": 2});
        let legacy = serde_json::json!({});
        let blank = serde_json::json!({"version": ""});
        assert_eq!(revision_from_manifest(&v1), "1");
        assert_eq!(revision_from_manifest(&v2), "2");
        // Pre-revision manifests get a defined identity instead of colliding
        // with a numbered one.
        assert_eq!(revision_from_manifest(&legacy), "0");
        assert_eq!(revision_from_manifest(&blank), "0");
        // Distinct revisions must never join the same soak.
        assert_ne!(revision_from_manifest(&v1), revision_from_manifest(&v2));
    }

    #[test]
    fn seeding_never_downgrades_a_newer_deployed_model() {
        let dir = std::env::temp_dir().join("gpo-shadow-seed-guard");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        // A deployed manifest at a HIGHER version than bundled.
        std::fs::write(
            dir.join("fish_v1.json"),
            serde_json::to_string_pretty(&slot_manifest("fish_v1", "7")).unwrap(),
        )
        .unwrap();
        let before = std::fs::read_to_string(dir.join("fish_v1.json")).unwrap();

        let candidates = vec![PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models")];
        let _ = seed_shadow_models(&candidates, &dir);

        let after = std::fs::read_to_string(dir.join("fish_v1.json")).unwrap();
        assert_eq!(before, after, "a promoted model must survive an app restart");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
