//! Shadow inference: tract-powered ONNX observation with NO macro control
//! (v5.4.0 plan).
//!
//! Control-impossibility is structural, not promised:
//! - `preprocess_rgba` / `infer_logits` / `softmax_temp` are pure functions
//!   of pixels. They receive no `Ctx`, no input handles, no settings.
//! - The global engine only loads models and runs them; callers (machine.rs)
//!   may LOG the observations and nothing else.
//! - The production provider (`ml_model.rs`) is untouched: `available()`
//!   stays false, so nothing here can activate control.
//!
//! Preprocessing MUST equal training preprocessing (pad-to-square black,
//! bilinear resize, /255, dataset mean/std — see each model's manifest
//! `preprocess` block, generated by scripts/gen_shadow_deploy.py from the
//! real run configs). Equivalence is proven by the fixture test below
//! (PIL BILINEAR vs this manual bilinear: tolerance 5e-3, argmax exact).

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use serde::{Deserialize, Serialize};
use tract_onnx::prelude::*;

use super::ml_model::verify_weights;

/// Files bundled with the app that may seed `%APPDATA%/models/`.
pub const SHADOW_MODEL_FILES: &[(&str, &str)] =
    &[("state_v1.onnx", "state_v1.json"), ("fish_v1.onnx", "fish_v1.json")];

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreprocessSpec {
    pub pad: String,
    pub resize: String,
    pub size: usize,
    pub mean: [f32; 3],
    pub std: [f32; 3],
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ShadowManifest {
    #[serde(flatten)]
    base: super::ml_model::ModelManifest,
    temperature: f32,
    #[serde(default)]
    test_accuracy: Option<f32>,
    preprocess: PreprocessSpec,
}

/// Concrete tract session type (fact/op/plan pinned for this build).
pub type ShadowSession =
    RunnableModel<TypedFact, Box<dyn TypedOp>, Graph<TypedFact, Box<dyn TypedOp>>>;

pub struct ShadowModel {
    pub name: String,
    pub classes: Vec<String>,
    pub temperature: f32,
    pub test_accuracy: Option<f32>,
    pub spec: PreprocessSpec,
    session: ShadowSession,
}

pub struct ShadowEngine {
    pub models_dir: PathBuf,
    pub models: HashMap<String, ShadowModel>,
}

fn load_one(models_dir: &Path, onnx_name: &str, json_name: &str) -> Result<ShadowModel, String> {
    let json_path = models_dir.join(json_name);
    let onnx_path = models_dir.join(onnx_name);
    let raw = std::fs::read_to_string(&json_path).map_err(|e| format!("{json_name}: {e}"))?;
    let m: ShadowManifest =
        serde_json::from_str(&raw).map_err(|e| format!("{json_name} invalid: {e}"))?;
    if m.base.runtime != "tract" {
        return Err(format!("{}: runtime '{}' is not this tract build", json_name, m.base.runtime));
    }
    verify_weights(&m.base, &onnx_path.to_path_buf()).map_err(|e| e.to_string())?;
    let mut typed = tract_onnx::onnx()
        .model_for_path(&onnx_path)
        .map_err(|e| format!("{onnx_name} load: {e}"))?;
    typed
        .set_input_fact(0, f32::fact([1, 3, m.preprocess.size, m.preprocess.size]).into())
        .map_err(|e| format!("{onnx_name} input fact: {e}"))?;
    // NOTE: no into_optimized(): the dynamo-exported graph contains a Conv
    // formulation whose optimizer analysis tract 0.22 rejects (ConvHir).
    // into_typed + into_runnable executes the same semantics without the
    // failing optimizer pass; the fixture argmax test below proves
    // end-to-end agreement with torch.
    let session = typed
        .into_typed()
        .map_err(|e| format!("{onnx_name} typed: {e}"))?
        .into_runnable()
        .map_err(|e| format!("{onnx_name} runnable: {e}"))?;
    // Shape-check: single output of [1, n_classes].
    Ok(ShadowModel {
        name: m.base.name.clone(),
        classes: m.base.classes.clone(),
        temperature: m.temperature,
        test_accuracy: m.test_accuracy,
        spec: m.preprocess,
        session,
    })
}

impl ShadowEngine {
    /// Load every deployable shadow model from `models_dir`. Missing files
    /// are skipped (engine still usable with the rest); corrupt files are
    /// errors (never silently run wrong weights).
    pub fn load(models_dir: &Path) -> Result<Self, String> {
        let mut models = HashMap::new();
        let mut missing = 0;
        for (onnx, json) in SHADOW_MODEL_FILES {
            if !models_dir.join(json).exists() || !models_dir.join(onnx).exists() {
                missing += 1;
                continue;
            }
            let m = load_one(models_dir, onnx, json)?;
            models.insert(m.name.clone(), m);
        }
        if models.is_empty() {
            return Err(format!("no shadow models in {}", models_dir.display()));
        }
        tracing::info!("shadow inference: loaded {} model(s) ({} missing)", models.len(), missing);
        Ok(Self { models_dir: models_dir.to_path_buf(), models })
    }

    pub fn model_names(&self) -> Vec<String> {
        let mut v: Vec<String> = self.models.keys().cloned().collect();
        v.sort();
        v
    }

    /// Pure inference: CHW pixels -> class probabilities. No side effects.
    pub fn infer_probs(&self, name: &str, chw: &[f32]) -> Option<Vec<(String, f32)>> {
        let m = self.models.get(name)?;
        let s = m.spec.size;
        if chw.len() != 3 * s * s {
            return None;
        }
        let shape = [1, 3, s, s];
        let input = Tensor::from_shape(&shape, chw).ok()?;
        let out = m.session.run(tvec![input.into()]).ok()?;
        let logits = out[0].to_array_view::<f32>().ok()?;
        let flat: Vec<f32> = logits.iter().cloned().collect();
        if flat.len() != m.classes.len() {
            return None;
        }
        let probs = softmax_temp(&flat, m.temperature);
        Some(m.classes.iter().cloned().zip(probs).collect())
    }
}

/// RGBA frame -> CHW model input. Manual bilinear with PIL-compatible
/// center mapping: src=(dst+0.5)*scale-0.5, edge-clamped.
pub fn preprocess_rgba(rgba: &[u8], w: usize, h: usize, spec: &PreprocessSpec) -> Option<Vec<f32>> {
    if rgba.len() < w * h * 4 || w == 0 || h == 0 {
        return None;
    }
    // RGB, then pad to square (black).
    let side = w.max(h);
    let mut sq = vec![0u8; side * side * 3];
    for y in 0..h {
        for x in 0..w {
            let s = (y * w + x) * 4;
            let dx = (side - w) / 2 + x;
            let dy = (side - h) / 2 + y;
            let d = (dy * side + dx) * 3;
            sq[d] = rgba[s];
            sq[d + 1] = rgba[s + 1];
            sq[d + 2] = rgba[s + 2];
        }
    }
    // Bilinear resize to size x size, per channel.
    let n = spec.size;
    let mut out = vec![0f32; 3 * n * n];
    let sx = side as f32 / n as f32;
    let sy = side as f32 / n as f32;
    for c in 0..3 {
        for dy in 0..n {
            let src_y = (dy as f32 + 0.5) * sy - 0.5;
            let y0 = (src_y.floor() as isize).clamp(0, side as isize - 1) as usize;
            let y1 = (y0 + 1).min(side - 1);
            let fy = (src_y - y0 as f32).clamp(0.0, 1.0);
            for dx in 0..n {
                let src_x = (dx as f32 + 0.5) * sx - 0.5;
                let x0 = (src_x.floor() as isize).clamp(0, side as isize - 1) as usize;
                let x1 = (x0 + 1).min(side - 1);
                let fx = (src_x - x0 as f32).clamp(0.0, 1.0);
                let at = |xx: usize, yy: usize| sq[(yy * side + xx) * 3 + c] as f32 / 255.0;
                let v = at(x0, y0) * (1.0 - fx) * (1.0 - fy)
                    + at(x1, y0) * fx * (1.0 - fy)
                    + at(x0, y1) * (1.0 - fx) * fy
                    + at(x1, y1) * fx * fy;
                out[(c * n + dy) * n + dx] = (v - spec.mean[c]) / spec.std[c];
            }
        }
    }
    Some(out)
}

pub fn softmax_temp(logits: &[f32], temperature: f32) -> Vec<f32> {
    let t = temperature.max(1e-6);
    let m = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let ex: Vec<f32> = logits.iter().map(|v| ((v - m) / t).exp()).collect();
    let s: f32 = ex.iter().sum();
    ex.iter().map(|v| v / s).collect()
}

static ENGINE: OnceLock<Mutex<ShadowEngine>> = OnceLock::new();

/// Get-or-load the process-wide shadow engine. First call pays model load.
pub fn engine(models_dir: &Path) -> Option<std::sync::MutexGuard<'static, ShadowEngine>> {
    let cell = ENGINE.get_or_init(|| {
        Mutex::new(ShadowEngine { models_dir: models_dir.to_path_buf(), models: HashMap::new() })
    });
    let mut guard = cell.lock().ok()?;
    if guard.models.is_empty() {
        match ShadowEngine::load(models_dir) {
            Ok(e) => *guard = e,
            Err(err) => {
                tracing::warn!("shadow inference unavailable: {err}");
                return None;
            }
        }
    }
    Some(guard)
}

/// Seed `%APPDATA%/models` from bundled candidates. Copies a file only when
/// missing or checksum-divergent, then re-verifies. Allowlist enforced.
pub fn seed_shadow_models(candidates: &[PathBuf], models_dir: &Path) -> Vec<String> {
    let _ = std::fs::create_dir_all(models_dir);
    let mut seeded = Vec::new();
    for (onnx, json) in SHADOW_MODEL_FILES {
        let src_json = candidates.iter().map(|c| c.join(json)).find(|p| p.exists());
        let src_onnx = candidates.iter().map(|c| c.join(onnx)).find(|p| p.exists());
        let (Some(sj), Some(so)) = (src_json, src_onnx) else { continue };
        let want_json = std::fs::read(&sj).unwrap_or_default();
        let want_onnx = std::fs::read(&so).unwrap_or_default();
        if want_json.is_empty() || want_onnx.is_empty() {
            continue;
        }
        let dj = models_dir.join(json);
        let do_ = models_dir.join(onnx);
        let same = std::fs::read(&dj).map(|b| b == want_json).unwrap_or(false)
            && std::fs::read(&do_).map(|b| b == want_onnx).unwrap_or(false);
        if !same
            && (std::fs::write(&dj, &want_json).is_err() || std::fs::write(&do_, &want_onnx).is_err())
        {
            tracing::warn!("shadow seed: write failed for {onnx}");
            continue;
        }
        // Verify what is on disk (seeded or pre-existing) before trusting.
        match load_one(models_dir, onnx, json) {
            Ok(_) => seeded.push(onnx.to_string()),
            Err(e) => tracing::warn!("shadow seed: deployed {onnx} rejected: {e}"),
        }
    }
    seeded
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/shadow")
    }

    fn read_f32(name: &str) -> Vec<f32> {
        let bytes = std::fs::read(fixture_dir().join(name)).unwrap();
        assert_eq!(bytes.len() % 4, 0);
        bytes.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
    }

    fn spec_for(model: &str) -> PreprocessSpec {
        let raw = std::fs::read_to_string(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!("models/{model}.json")),
        )
        .unwrap();
        let v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let p = &v["preprocess"];
        let arr = |k: &str| -> [f32; 3] {
            let a = p[k].as_array().unwrap();
            [a[0].as_f64().unwrap() as f32, a[1].as_f64().unwrap() as f32, a[2].as_f64().unwrap() as f32]
        };
        PreprocessSpec {
            pad: p["pad"].as_str().unwrap().into(),
            resize: p["resize"].as_str().unwrap().into(),
            size: p["size"].as_u64().unwrap() as usize,
            mean: arr("mean"),
            std: arr("std"),
        }
    }

    #[test]
    fn preprocess_matches_python_fixture() {
        let png = std::fs::read(fixture_dir().join("fixture.png")).unwrap();
        let img = image::load_from_memory(&png).unwrap().to_rgba8();
        let (w, h) = (img.width() as usize, img.height() as usize);
        let meta: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(fixture_dir().join("expected.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(meta["png_sha256"].as_str().unwrap(), &{
            // cross-check the fixture itself via the repo's sha helper
            super::super::ml_model::sha256_file(&fixture_dir().join("fixture.png")).unwrap()
        });
        for model in ["state_v1", "fish_v1"] {
            let spec = spec_for(model);
            let got = preprocess_rgba(img.as_raw(), w, h, &spec).unwrap();
            let want = read_f32(&format!("{model}.f32"));
            assert_eq!(got.len(), want.len());
            let worst = got.iter().zip(want.iter()).map(|(a, b)| (a - b).abs()).fold(0f32, f32::max);
            let tol = meta["tolerance_max_abs_diff"].as_f64().unwrap() as f32;
            assert!(worst < tol, "{model} preprocess drift: worst {worst} >= tol {tol}");
        }
    }

    #[test]
    fn deployed_models_predict_fixture_argmax() {
        let models_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        let engine = ShadowEngine::load(&models_dir).expect("repo models must load");
        let png = std::fs::read(fixture_dir().join("fixture.png")).unwrap();
        let img = image::load_from_memory(&png).unwrap().to_rgba8();
        let (w, h) = (img.width() as usize, img.height() as usize);
        let meta: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(fixture_dir().join("expected.json")).unwrap(),
        )
        .unwrap();
        for model in ["state_v1", "fish_v1"] {
            let spec = spec_for(model);
            let chw = preprocess_rgba(img.as_raw(), w, h, &spec).unwrap();
            let probs = engine.infer_probs(model, &chw).expect("infer must succeed");
            let (best, _) =
                probs.iter().max_by(|a, b| a.1.partial_cmp(&b.1).unwrap()).unwrap();
            let want_idx = meta["argmax"][model].as_u64().unwrap() as usize;
            let want_class = &engine.models[model].classes[want_idx];
            assert_eq!(best, want_class, "{model} argmax diverged from torch (preprocess or runtime drift)");
        }
    }

    #[test]
    fn corrupt_weights_never_load() {
        let dir = std::env::temp_dir().join("gpo-shadow-corrupt");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        std::fs::copy(repo.join("state_v1.json"), dir.join("state_v1.json")).unwrap();
        // Truncated weights: manifest sha will not match.
        let w = std::fs::read(repo.join("state_v1.onnx")).unwrap();
        std::fs::write(dir.join("state_v1.onnx"), &w[..w.len() / 2]).unwrap();
        let err = match ShadowEngine::load(&dir) {
            Ok(_) => panic!("corrupt weights must refuse to load"),
            Err(e) => e,
        };
        // Contract: corrupt files are hard errors (checksum), never silent.
        assert!(err.contains("checksum mismatch"), "corrupt weights must refuse: {err}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn seeding_deploys_verifiable_models() {
        let dir = std::env::temp_dir().join("gpo-shadow-seed");
        let _ = std::fs::remove_dir_all(&dir);
        let repo_models = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models");
        let seeded = seed_shadow_models(&[repo_models], &dir.join("models"));
        assert_eq!(seeded.len(), 2, "both bundled models must seed, got {seeded:?}");
        // Seeded copies load and stay byte-identical (no silent rewrite).
        let engine = ShadowEngine::load(&dir.join("models")).expect("seeded models must load");
        assert_eq!(engine.models.len(), 2);
        // Second seed is a no-op rewrite-wise but still verifies.
        let seeded2 = seed_shadow_models(
            &[PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("models")],
            &dir.join("models"),
        );
        assert_eq!(seeded2.len(), 2);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn softmax_temp_matches_definition() {
        let p = softmax_temp(&[2.0, 1.0, 0.0], 1.0);
        let s: f32 = p.iter().sum();
        assert!((s - 1.0).abs() < 1e-6);
        assert!(p[0] > p[1] && p[1] > p[2]);
        // Lower temperature sharpens.
        let sharp = softmax_temp(&[2.0, 1.0, 0.0], 0.15);
        assert!(sharp[0] > p[0]);
    }
}
